### ISSUE TITLE
Can't Open/Delete SP world

### ISSUE THREAD

**Issue by ProxyPlayerHD** [Regner6/Afterlife-Souls-Reborn-feedback#1]
after seeing that there's a Frozensoul Pack, i instantly Downloaded it.
aaaaand here's the First Problem i have:
when i try to Delete/open a SP world, it just does Nothing.
luckly i always have the FTB Console in the background.
here's the Error for loading a World:
http://pastebin.com/UgHn1sjW

and here the Deleting:
http://pastebin.com/wFvBiLG7
(it says that it successfully deleted the world, but it's still there)

hope that the Server won't throw out the same (or simalar) Error...

**Comment by Regner6** [comment]
Issue fixed in the next update

**Comment by ProxyPlayerHD** [comment]
cool, thx! :D
